---
sonar_root: /opt/sonar/
sonar_jdbc_username: sonar
sonar_jdbc_password: mysql!23
sonar_jdbc_url: jdbc:mysql://{{mysql_ip}}:3306/sonar?useUnicode=true&characterEncoding=utf8&rewriteBatchedStatements=true&useConfigs=maxPerformance&useSSL=false
