---
- name: Repositories update
  yum: update_cache=yes name=* state=latest update_cache=yes
 # when: ansible_os_family == 'CentOS' or ansible_os_family == 'RedHat'
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat'
- name: Repositories update for Debian
  apt: update_cache=yes cache_valid_time=1500 upgrade=dist
  when: ansible_os_family == 'Debian' or ansible_os_family == 'Ubuntu'
